# Generated by Django 2.2.5 on 2019-10-15 19:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0031_remove_student_classrooms'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('external_id', models.CharField(blank=True, max_length=16, null=True)),
                ('address', models.CharField(blank=True, max_length=128, null=True)),
                ('city', models.CharField(blank=True, max_length=32, null=True)),
                ('state', models.CharField(blank=True, max_length=32, null=True)),
                ('country', models.CharField(blank=True, max_length=64, null=True)),
                ('zip', models.CharField(blank=True, max_length=16, null=True)),
                ('code', models.CharField(max_length=8)),
            ],
        ),
        migrations.RenameModel(
            old_name='Teacher',
            new_name='Staff',
        ),
        migrations.DeleteModel(
            name='Classroom',
        ),
        migrations.AddField(
            model_name='school',
            name='owners',
            field=models.ManyToManyField(related_name='schools_owned', to='teacher.Staff'),
        ),
        migrations.AddField(
            model_name='school',
            name='staff',
            field=models.ManyToManyField(related_name='schools_staffed', to='teacher.Staff'),
        ),
    ]
