# Generated by Django 2.2.5 on 2019-10-15 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20191015_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
