# Generated by Django 2.2.5 on 2019-10-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20191015_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='student_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='schools_owned', to='teacher.Staff'),
        ),
        migrations.AlterField(
            model_name='school',
            name='staff',
            field=models.ManyToManyField(blank=True, related_name='schools_staffed', to='teacher.Staff'),
        ),
    ]
