# Generated by Django 2.2.5 on 2019-10-08 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliouser',
            name='email',
            field=models.CharField(max_length=256),
        ),
    ]
