# Generated by Django 2.2.5 on 2019-09-19 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='tempLocation',
            new_name='temp_location',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='dateTimeAdded',
            new_name='date_time_added',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='itemId',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='itemType',
            new_name='item_type',
        ),
    ]
