# Generated by Django 2.2.5 on 2019-09-18 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20190917_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='classrooms',
        ),
    ]
