# Generated by Django 2.2.5 on 2019-09-25 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20190919_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='image',
            field=models.URLField(default='/static/link_default.svg', max_length=512),
        ),
    ]
