# Generated by Django 2.2.5 on 2019-09-18 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
        ('student', '0003_remove_student_classrooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='classrooms',
            field=models.ManyToManyField(blank=True, related_name='students', to='teacher.Classroom'),
        ),
    ]
