# Generated by Django 2.2.5 on 2019-09-25 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_link_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='image',
            field=models.URLField(default='/static/default_images/link.svg', max_length=512),
        ),
    ]
