# Generated by Django 2.2.5 on 2019-09-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20190925_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='image',
            field=models.CharField(default='/static/student/default_images/link.svg', max_length=512),
        ),
    ]
