# Generated by Django 2.2.5 on 2019-09-30 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20190930_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_id',
            new_name='sub_item_id',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item_type',
            new_name='sub_item_type',
        ),
    ]
