# Generated by Django 2.2.5 on 2019-10-01 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_auto_20191001_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='temp_location',
        ),
    ]
