# Generated by Django 2.2.5 on 2019-10-01 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_photo_gallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='gallery',
            new_name='parent_gallery',
        ),
        migrations.AddField(
            model_name='gallery',
            name='image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.Photo'),
        ),
    ]
