# Generated by Django 2.2.5 on 2019-10-01 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_auto_20191001_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='image',
            new_name='photo',
        ),
    ]
