# Generated by Django 2.2.5 on 2019-10-08 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_auto_20191007_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='images/7764a2e136b8425b95efaba110d12681/'),
        ),
    ]
