# Generated by Django 2.2.5 on 2019-10-08 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_auto_20191008_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='images/86e501c1f80440edaf97f597fb6719c9/'),
        ),
    ]
