# Generated by Django 2.2.5 on 2019-10-08 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_auto_20191008_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='images/2e1d037853384a499e9bd15796804448/'),
        ),
    ]
