# Generated by Django 2.2.5 on 2019-10-08 22:35

from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0022_auto_20191008_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=student.models.get_image_upload_path),
        ),
    ]
