# Generated by Django 2.2.5 on 2019-10-10 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0026_auto_20191009_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='icon',
            field=models.CharField(default='fas fa-file', max_length=32),
        ),
    ]
