# Generated by Django 2.2.5 on 2019-10-11 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0027_document_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='google_credentials',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
