# Generated by Django 2.2.5 on 2019-10-15 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0030_auto_20191015_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='classrooms',
        ),
    ]
