# Generated by Django 2.2.5 on 2019-10-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0031_remove_student_classrooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='school_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
