# Generated by Django 2.2.5 on 2019-10-18 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0032_student_school_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sub_item_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'student'), ('model', 'link')), models.Q(('app_label', 'student'), ('model', 'gallery')), models.Q(('app_label', 'student'), ('model', 'document')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
