from .base import *

DEBUG = os.environ['DJANGO_DEBUG']

ALLOWED_HOSTS = ['showcaseedu.com', 'localhost', 'www.showcaseedu.com']

SOCIAL_AUTH_REDIRECT_IS_HTTPS = True
SECURE_SSL_REDIRECT = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_HSTS_SECONDS = 2592000
SECURE_HSTS_PRELOAD = True
SECURE_HSTS_INCLUDE_SUBDOMAINS = True